-- MySQL Script generated by MySQL Workbench
-- 06/11/15 10:49:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tree_demo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tree_demo` ;

-- -----------------------------------------------------
-- Schema tree_demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tree_demo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tree_demo` ;

-- -----------------------------------------------------
-- Table `tree_demo`.`node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tree_demo`.`node` (
  `node_id` BIGINT(20) NOT NULL,
  `node_name` VARCHAR(100) NOT NULL,
  `left_value` BIGINT(20) NOT NULL,
  `right_value` BIGINT(20) NOT NULL,
  `parent_id` BIGINT(20) NULL,
  PRIMARY KEY (`node_id`),
  CONSTRAINT `fk_node_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `tree_demo`.`node` (`node_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `IX_node_parent_id` ON `tree_demo`.`node` (`parent_id` ASC);

CREATE INDEX `IX_node_name` ON `tree_demo`.`node` (`node_name` ASC);

CREATE INDEX `IX_node_left_value` ON `tree_demo`.`node` (`left_value` ASC);

CREATE INDEX `IX_node_right_value` ON `tree_demo`.`node` (`right_value` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
